server:
  port: 8081

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/bbaemin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    pool:
      max-size: 100
      validation-query: SELECT 1
  kafka:
    bootstrap-servers: 192.168.219.101:9092

logging:
  level:
    org.springframework.r2dbc: debug

service:
  admin: http://localhost:8080
  user: http://localhost:8081
