# test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:bbaemin;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    bootstrap-servers: 192.168.219.101:9092
    consumer:
      auto-offset-reset: earliest

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  pattern:
    console: '[%d{yyyy:MM:dd HH:mm:ss}] %-5level %logger{36}:%line - %msg%n'
